### ISSUE TITLE
Team/channel-scoped rules

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/mattermost-plugin-autolink#10]
Especially when autolinking JIRA tickets (`FOO-\d+`) or GitHub issues (`#\d+`), chances are good that they only matter in certain channels/teams. and make no sense somewhere else (or should link to a different target),

Currently the only option is to add only rules that are useful instance-wide and not do any autolinking for anything that's less global. It would be nice if rules could be defined on the team and/or channel level.

**Comment by outofcontrol** [comment]
This is highly desired in our Gitlab install also, where we have many groups with many repositories in each.

**Comment by scottleedavis** [comment]
Hello @hanzei  I would like to contribute this.  My company uses this, and it would be helpful for us to only allow certain autolinks in certain channels.

**Comment by hanzei** [comment]
Thanks @scottleedavis for working on this!

**Comment by scottleedavis** [comment]
@ThiefMaster @outofcontrol Do either of you have any use cases for a channel scope, across teams?

https://github.com/mattermost/mattermost-plugin-autolink/pull/43#issuecomment-468860186

**Comment by ThiefMaster** [comment]
Channel scope without mentioning a team: no, seems somewhat useless, unless someone wants e.g. off-topic to have the same rules in all teams. seems not very useful though.

`teamname/channelname` is very useful though, e.g. for a development team that wants to autolink `#123` or `project#123` to their github issue tracker without affecting all other channels. I would very much use that one!

**Comment by scottleedavis** [comment]
Fantastic feedback, thank you @ThiefMaster

**Comment by outofcontrol** [comment]
@scottleedavis Across teams no. Within teams how @ThiefMaster describes it, would be quite nice to have.

**Comment by scottleedavis** [comment]
alright, majority wins.  :)

**Comment by jasonblais** [comment]
@scottleedavis Does your PR (#43) cover this open issue?

**Comment by scottleedavis** [comment]
yes @jasonblais
