### ISSUE TITLE
Use a better regex engine

### ISSUE THREAD

**Issue by maaaat** [mattermost/mattermost-plugin-autolink#111]
The regex engine used by the plugin is a bit limited. It does support the `(?P<name>)` extension but that seems to be the only one. Switching to PCRE would bring support for all the popular `(?)` extensions that make regex creation go from tears of pain to tears of joy.

The example I am running into is this regex:
```
(?P<ID>[A-Z]+-(?<!AP-)[0-9]+)
```

Which would match anything that look like a JIRA ID, with an exception for `AP-\d` because in our case `AP` is not a JIRA project name but the acronym of a company product.

**Comment by levb** [comment]
We are using the go regexp package and are not planning to support PCRE yet
