### ISSUE TITLE
Make it Easy: Add and update patterns from Autolink config screen

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-autolink#132]
Currently, all autolink patterns and regexes must be set using a set of cumbersome slash commands. We want to make it easy for an admin to add a Regular Expression and template to the list of Auotlink rules.  Using Custom Settings components on the system console, Update the AutoLink admin UI to allow users to modify data for autolink from the system console rather than using the slash command. 

This would allow a user to save a Link Name, Pattern, Template and optionally set a team for scope. As is the case with the slash commands, this UI is only manipulating the data in the config.json right now - but another important ticket is to move the configuration off of the config.json file and store it in the Key Value Store - which is where we store persistent data.

![2020-09-24_11-15-04](https://user-images.githubusercontent.com/915956/94951067-82be9400-0498-11eb-802b-95c5181b8d33.png)

**Comment by hanzei** [comment]
@aaronrothschild Is this a duplicate of https://github.com/mattermost/mattermost-plugin-autolink/issues/31? maybe you move your comment over into that issue?

**Comment by aaronrothschild** [comment]
This is basically a duplicate of #31 - Closing.
