### ISSUE TITLE
Can this be configured per channel?

### ISSUE THREAD

**Issue by nikolalukovic** [mattermost/mattermost-plugin-autolink#135]
I couldn't find the info in the README so I'm just asking here. Is it possible to configure this plugin to work per channel? Different configurations for different channels?

**Comment by hanzei** [comment]
That is in deed possible. You need to specify the `Scope` of your link. See https://github.com/mattermost/mattermost-plugin-autolink#examples

**Comment by nikolalukovic** [comment]
Great! Thanks for the info!
