### ISSUE TITLE
Failing tests do not appear properly in GitHub/CI

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-autolink#136]
@levb @iomodo So it seems that I missed the fact that my change actually makes already existing tests fail. I ignored the failed part of CI on GitHub because of its name - "coverage". I assumed it's about percentage of coverage and not about tests. I've logged into Circle CI a couple of minutes ago to see the details.

I think that unit tests treating the `(` character as non-boundary need a discussion.

But the second group of fails is much more interesting: more than one pattern/template seems to be applied to a single text fragment and MM-12345 gets expanded twice.

I'm going to experiment a bit with the code despite my lack of knowledge about Go ;)

BTW, with a more complicated pattern `(?P<MattermostNonWordPrefix>(^|^\(|\s|\s\())` tests pass but I have to think if it would be a solution or just a dirty workaround.

_Originally posted by @wodny in https://github.com/mattermost/mattermost-plugin-autolink/pull/130#issuecomment-700146504_

**Comment by catalintomai** [comment]
Fix for autolink only (for now).
