### ISSUE TITLE
Plugin should be allowed to work with bot accounts

### ISSUE THREAD

**Issue by njnatale-lm** [mattermost/mattermost-plugin-autolink#141]
It looks like this plugin purposely blocks re-writes of posts by bots. This should be a configurable option, either globally or per each autolink item? I had a really great idea for using this plugin with my own bot, but now I cannot due to this limitation.

**Comment by njnatale-lm** [comment]
Further information: currently, I have a utility that posts messages as a bot. I would like it to tag users, but the user list fluctuates, and I don't want the list of users to be maintained in the the utility's code. So I'd like to use a codeword like `PEOPLE`  that will trigger the plugin to replace the word with direct `@person @person` mentions of all of the people. It seems right now that the plugin just ignores any messages from bots. We should have an option to do this, since in this instance, I definitely want it to apply to bot accounts too.

**Comment by rorist** [comment]
+1
