### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-autolink#144]
- [x] https://github.com/mattermost/mattermost-plugin-autolink/pull/143
- [x] https://github.com/mattermost/mattermost-plugin-autolink/pull/148
- [x] https://github.com/mattermost/mattermost-plugin-autolink/pull/160
- [x] https://github.com/mattermost/mattermost-plugin-autolink/issues/181
- [x] https://github.com/mattermost/mattermost-plugin-autolink/issues/180
- [ ] https://github.com/mattermost/mattermost-plugin-autolink/issues/188

**Comment by justinegeffen** [comment]
@hanzei, let me know if there are any doc updates for this. Thanks! :)

**Comment by hanzei** [comment]
@justinegeffen There aren't any doc updates need that I'm aware of.

**Comment by mickmister** [comment]
@DHaussermann @dipak-demansol @sibasankarnayak We are currently unsure if https://github.com/mattermost/mattermost-plugin-autolink/issues/188 should block this release. We would like to release this in a week if we are still unsure.

**Comment by mickmister** [comment]
We went ahead and released this without https://github.com/mattermost/mattermost-plugin-autolink/issues/188
