### ISSUE TITLE
Can I use this plugin to create mention groups?

### ISSUE THREAD

**Issue by ohze** [mattermost/mattermost-plugin-autolink#16]
Can I use this plugin to [Add custom user groups for mentions](https://mattermost.uservoice.com/forums/306457-general/suggestions/13792272-add-custom-user-groups-for-mentions)?
Ex, if the Pattern is "`@developers`", Template is "`@user1, @user2, @user3`"
then will those users receive notification when I post "`@developers hello!`"?

**Comment by derschatta** [comment]
I just tried, it works
`{
    "Pattern": "(\\@group)",
    "Template": "@user1 @user2"
 }`

**Comment by misss13** [comment]
As for the ones that struggled like me try adding:
`/autolink set [linkname] DisableNonWordPrefix true`
