### ISSUE TITLE
[QUESTION] Is possible to make calculation when the link is processed ?

### ISSUE THREAD

**Issue by nothing-fr** [mattermost/mattermost-plugin-autolink#161]
Hi,

Is possible to make calculation when the link is processed ?

I want to use autolink for our ticketing system, but my problem is : 
- Ticket ID is 6352
- ID in URL does not match : it's 6452 (the difference is always +100 with the ticket ID)

Is it possible to make transformation (add 100 to the ticket ID) before creating the link ? 

Thanks

**Comment by ThiefMaster** [comment]
Rewriting those links to a small webapp that does the translation for you might be easier...

**Comment by nothing-fr** [comment]
ok, thanks

**Comment by mickmister** [comment]
@nothing-fr You can write a small plugin that would do this translation. Check out the docs [here](https://developers.mattermost.com/extend/plugins), and join the [Toolkit](https://community-daily.mattermost.com/core/channels/developer-toolkit) channel on our community server to discuss some solutions to your requirements!
