### ISSUE TITLE
Version 0.2.0 shows up as 0.1.0 in the interface

### ISSUE THREAD

**Issue by derschatta** [mattermost/mattermost-plugin-autolink#18]
I just installed version 0.2.0 on Mattermost 5.1. In the interface it shows up like this.

![auto-link-0 2 0](https://user-images.githubusercontent.com/6513855/43437440-2e907bf0-94dd-11e8-94cd-9afcf09ea6a6.png)

**Comment by amyblais** [comment]
@coreyhulen ^ or let me know if I can help ask someone to test it out.

**Comment by jasonblais** [comment]
Confirmed on pre-release this is fixed on v0.3:

![image](https://user-images.githubusercontent.com/13119842/43553016-150bd70e-95bb-11e8-98e6-ab4a6f0740e1.png)

Okay to close the issue @derschatta?

**Comment by derschatta** [comment]
yes, thanks @jasonblais
