### ISSUE TITLE
Autolink admin user IDs requires spaces between commas

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-plugin-autolink#181]
![image](https://user-images.githubusercontent.com/1192780/149370550-ca286e57-cf79-4d91-aa9d-13051bc3ab32.png)

Appears to require spaces between commas are the admin features do not work.

**Comment by hanzei** [comment]
@dipak-demansol Could you please try to reproduce this?

**Comment by DHaussermann** [comment]
After further exploration - it seems that saving a 2nd user (or additional users) to the config only work intermittently.  

Regardless of if there is a whitespace character - saving the string with multiple users only works some of the time. This happpens regadless of if there is whitespace or if the string is valid such as `xntwk983abgbdgixdfhha3xcsc,x8xo6zmhhfnc3p4w6eqofky9uw`

We have confirmed that when the issue reproduces, the value also looks correct in the configuration file
![image](https://user-images.githubusercontent.com/35588783/151821339-fa01343c-7621-496e-b1e3-0ff97e54642c.png)

Removing the value and resaving the **same** string can solve the issue. It is not known why this is intermittent.

cc @hanzei

**Comment by hanzei** [comment]
Might be related to https://github.com/mattermost/mattermost-plugin-autolink/issues/180
