### ISSUE TITLE
Autolink logs "Markdown autolink did not match range text"

### ISSUE THREAD

**Issue by catalintomai** [mattermost/mattermost-plugin-autolink#188]
Hi team, not sure if this is the correct place to get some feedback on this:
Is there a reason why entering www.whatever.com in the chat box the error below appears on the log?

```
{"timestamp":"2022-03-15 05:20:36.471 +01:00","level":"error","msg":"Markdown autolink did not match range text, '[http://www.whatever.com'](http://www.whatever.com%27/) != 'www.whatever.com'","caller":"app/plugin_api.go:928","plugin_id":"mattermost-autolink"}
However, this does not seems to affect when entering whatever.com or http://whatever.com/ on the chat room.
```
Is this expected?

Mattermost message: https://community.mattermost.com/core/pl/rpyzuujifif7tkna48b7jgcpor
Jira ticket: https://mattermost.atlassian.net/browse/MM-42669

**Comment by dipak-demansol** [comment]
@catalintomai issue is regenerated, i will share a video on our developer Channel.

**Comment by dipak-demansol** [comment]
i regenerated the issue, the log is similar but its not exactly same, i got this log 
`"level":"error","msg":"Markdown autolink did not match range text, 'http://www.whatever.com' != 'www.whatever.com'","caller":"app/plugin_api.go:940","plugin_id":"mattermost-autolink"}
`

**Comment by maisnamrajusingh** [comment]
@sibasankarnayak @dipak-demansol  lets look into this one and see how often this occurs and if there is a fix needed.

**Comment by hanzei** [comment]
@maisnamrajusingh Can you please provide a status update on this issue?

**Comment by hanzei** [comment]
@maisnamrajusingh Gentle reminder

**Comment by maisnamrajusingh** [comment]
@hanzei  this was already communicated earlier during one of the calls and siba was issuing a fix for it.
