### ISSUE TITLE
Autolinking doesn't work when message is edited

### ISSUE THREAD

**Issue by tmotyl** [mattermost/mattermost-plugin-autolink#197]
I have a working rule for jira tickets with ORSU prefix like `ORSU-123`
It works fine until I add the match when editing the message.

![image](https://user-images.githubusercontent.com/515397/174738052-4fe60976-5d6b-4fb0-844d-78c8453f337c.png)

The second message was typed as "abc" at first, and then edited to become "abc ORSU-123"

**Comment by jprusch** [comment]
I can confirm this & was about to file a bug report

**Comment by mickmister** [comment]
Hi @tmotyl, there is a plugin setting "Apply plugin to updated posts as well as new posts". Do you have this setting enabled?

**Comment by asatkinson** [comment]
closing as this seems invalid
