### ISSUE TITLE
Hashtags inserted by autolink do not work

### ISSUE THREAD

**Issue by akhmerov** [mattermost/mattermost-plugin-autolink#20]
I wanted to use autolink to also tag the links by doing something like `[src](url "#tag")`, which is then picked up by the tag search.

Unfortunately autolink plugin v0.2 does not work correctly with hashtags.

To reproduce use the following substitution:
```json
"Pattern": "foo",
"Template": "#bar"
```
Then search for `#bar` and verify that the search does not find any results.

Editing the message after the substitution has occurred does produce the desired result.

**Comment by akhmerov** [comment]
Update: also confirmed this is still present in v0.3.

**Comment by levb** [comment]
This appears to work with 1.1

![image](https://user-images.githubusercontent.com/1187448/63440301-71c1d900-c3e4-11e9-85ee-d00b63c57e15.png)

**Comment by akhmerov** [comment]
I have verified that the problem persists with 1.1 on mattermost 5.12.4.

Note that the issue is not with *rendering* of the replaced text, but whether it shows up when searching for the hashtag.

To reproduce:

![image](https://user-images.githubusercontent.com/2069677/63442766-f38d2300-c433-11e9-8a3b-351ac80d08fb.png)

![image](https://user-images.githubusercontent.com/2069677/63442810-043d9900-c434-11e9-8aab-46f6963416f2.png)

**Comment by levb** [comment]
@akhmerov @aaronrothschild https://community.mattermost.com/core/pl/kjqkepha3irppxmbbtmnc17ruy - I don't think it's a plugin issue per se. Let's see what comes out of the conversation there, maybe a new ticket for the toolkit.

**Comment by levb** [comment]
As per https://community.mattermost.com/core/pl/kjqkepha3irppxmbbtmnc17ruy we need to add 
`post.Hashtags, _ = model.ParseHashtags(post.Message)` to `MessageWillBePosted` in order for the hashtags to work. I am going to mark this as a `Help Wanted` ticket now, @akhmerov interested in contributing the fix?

**Comment by akhmerov** [comment]
Sorry, I've no familiarity with the codebase, language. Given some time I would be able to hack something together, but I also don't have time :(
