### ISSUE TITLE
The plugin gives no feedback if the list link is empty

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-autolink#208]
If there are no links in the list, no response is shown after you run `/autolink list` 

This should return an ephemeral response or possibly show an empty table so there is visual feedback the command is working.

This is **not** a regression. I'm just documenting an old known issue.

Steps:
- Install and enable autolink plugin
- Ensure the config is set to allow user side slash command to manage links
- Ensure there are no links saved (or delete all existing links)
- Run `/autolink list`

**Observed**: No response from the plugin

**Comment by Viktor-Yakovchuk** [comment]
I want to try.

**Comment by hanzei** [comment]
Thanks @Viktor-Yakovchuk :+1:
