### ISSUE TITLE
Plugin disappear on mattermost 5.2 restart

### ISSUE THREAD

**Issue by matclab** [mattermost/mattermost-plugin-autolink#21]
The plugin works well, but it disappear upon mattermost 5.2 restart.

I don't know  how to investigate and  if the problem is on the plugin side or on mattermost side (zoom plugin stay installed).

**Comment by amyblais** [comment]
Hi @matclab!

Do you mean it disappears after each time you restart the server? Do you see any errors in Logs or the Console?

**Comment by matclab** [comment]
No errors on the server apart:
```
{"level":"error","ts":1535293294.0645885,"caller":"web/context.go:60","msg":"Plugin is not installed","path":"/api/v4/plugins/mattermost-autolink/enable","request_id":"ecnz13botfre58hkncndx9
1x7y","ip_addr":"78.229.28.161","user_id":"1bns1c8sap8affgj9w9k8nhcta","method":"POST","err_where":"EnablePlugin","http_code":400,"err_details":""} 
```
I have to understand where the plugins are installed in mattermost v5.2. As I run it from a docker container, it is possible it is installed outside of the volumes defined in the docker-compose.yml file and as such not saved across docker container restart.

I think we can close this ticket as it probably comes from mattermost itself or from the way it is configured. I will comment back here once I've solved the problem.

**Comment by matclab** [comment]
Just for reference, I launch mattermost via docker compose, and `/mattermost/plugins` was not mounted to a persistent volume, thus installed volume disappeared when restarting the docker services.
Adding a line `/srv/docker/mattermost/app/mattermost/plugins:/mattermost/plugins:rw` to the docker `volumes` solves the problem.

**Comment by frakman1** [comment]
The docker-compose also mentions a `/mattermost/client/plugins` folder. What is that and how is it different from `/mattermost/plugins` ?
