### ISSUE TITLE
 Problem with opening and closing brackets 

### ISSUE THREAD

**Issue by derschatta** [mattermost/mattermost-plugin-autolink#24]
This is related to #17 which fixes a bug where text was not autolinked if there was a following punctuation mark.

The same bug occurs if brackets are used. Like in `there is a bug (see EXA-1234)`.

**Comment by lumbric** [comment]
Hmm the case `there are bugs (EXA-1234) and more things` is a bit more diifficult to be fixed. Simply adding the `(` to the regex breaks the tests.

**Comment by lumbric** [comment]
Hm I should have added the brackets in the first version of the pull request in #23, sorry...   It's still not perfect, but I think #25 is another improvement. @coreyhulen, could you have another quick look at #25?

**Comment by coreyhulen** [comment]
Looks good.
