### ISSUE TITLE
Updated posts are not processed

### ISSUE THREAD

**Issue by grubbins** [mattermost/mattermost-plugin-autolink#36]
If a post is edited to fix a typo, replacements are not applied. The plugin should handle the `MessageWillBeUpdated` hook too.

**Comment by grubbins** [comment]
I tried to fix this by adding that hook, but it is still not working :/
Not sure what the problem is at the moment.

**Comment by hanzei** [comment]
Thanks for the report @grubbins.

I'm not sure that this is something we really want. The main problem is that users have no possibility to fix posts that where wrongly edited by the plugin.

**Comment by grubbins** [comment]
Actually I think there are ways to fix posts. For example, if my text is replaced with an unwanted link, I can modify the text so that it does not match any more, or put it in a code block, or similar.

Conversely, consider using this plugin for replacing Jira ticket numbers with links (as I have set up). It is very confusing and irritating to users that this works on first posting, but does not work if they edit their post to add a Jira ticket number.

In our MM installation we will definitely want to keep the replacements on post updates. It could be a config option for each pattern?

**Comment by hanzei** [comment]
> Actually I think there are ways to fix posts. For example, if my text is replaced with an unwanted link, I can modify the text so that it does not match any more, or put it in a code block, or similar.

But how does a user know, what the pattern is? The normal users doesn't even know this plugins exists and might not even not what a plugin is. The changes to a post happen "magically" and users don't know why. Adding a config option doesn't fix this problem.

@coreyhulen What do you think?

**Comment by jespino** [comment]
Maybe we can add a "pattern" flag to allow to work on updates. Normally a lot of patterns are idempotent, so is not a big deal, but for that cases where you are not able to handle properly editions, you can disable it per-pattern (or maybe enable it if we set it as false by default).

**Comment by hanzei** [comment]
I would rather add a undo function. User should have the control over there own posts.

My fear is that posts get mangled and a user doesn't know how to fix this, like in #19.

**Comment by hanzei** [comment]
I see that an undo function is out of scope.

But flagging pattern can still result in the problem I described above. Are the other solutions you can think of? I'm running out of ideas.

**Comment by jespino** [comment]
I'll go for the flagging pattern approach for now, which will allow our uses to enable it for editions under his own responsability. Is better than nothing, and probably we can add another strategy later.

**Comment by levb** [comment]
To be clear on the proposed course of action:
1. Add a `EnableOnUpdate` default `false` to Link config properties.
2. Implement a `MessageWillBeUpdated` hook that will only apply the links with `EnableOnUpdate` set.
@hanzei @jespino please confirm.

**Comment by jespino** [comment]
@levb Yes, I think so

**Comment by jasonblais** [comment]
@levb @grubbins is this one resolved with #79?

**Comment by grubbins** [comment]
> @levb @grubbins is this one resolved with #79?

Yes :)

**Comment by jasonblais** [comment]
Great! Thanks so much @grubbins :D
