### ISSUE TITLE
Prevent autolinks in code-sections

### ISSUE THREAD

**Issue by obreitwi** [mattermost/mattermost-plugin-autolink#4]
As the title says, when enabling `mattermost-plugin-autolink`, the autolinks are also replaced in `code`-sections.

So, for example,
<pre>
```
LHS
```
</pre>
is expanded to
<pre>
```
[LHS](https://docs.mattermost.com/process/training.html#lhs)
```
</pre>
which breaks copy-pasting code snippets whenever they contain a matching regular expression.

Backtick-escaped inline code ~~seems to be unaffected~~ is affected when surrounded by spaces.

**Comment by coreyhulen** [comment]
0.2.0 should address this issue.

**Comment by ThiefMaster** [comment]
Assuming this is already running on pre-release.mattermost.com, the 4-space-indent code block syntax is not covered:

```
    MM-12345
```

was converted to

```
[MM-12345](https://mattermost.atlassian.net/browse/MM-12345)
```

**Comment by obreitwi** [comment]
Thank you, the issue is fixed for us!
