### ISSUE TITLE
Unify handling of opening and closing parentheses

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/mattermost-plugin-autolink#40]
#24 added support so a message like `(see GH-1234)` can have `GH-1234` autolinked, but the other way round doesn't work, so `(GH-1234 might solve your bug)` won't be autolinked. 

This can already be worked around by enabling DisableNonWordPrefix and then using a custom regex to specify the boundary, but I think more consistent default logic makes more sense.

**Comment by jespino** [comment]
Yes, that would be great, I have to think about it, maybe we can have another flag to allow that or a special field to specified a list of valid extra prefixes, like `(`, `{`, `,` or whatever.

**Comment by jasonblais** [comment]
FYI @levb @jfrerich This is one bug which would get noticed and reported as an issue in a GA release

**Comment by levb** [comment]
I'd appear that post 1.0 we probably want to change the semantics as:
[x] only match entire words
    word start separators:
        [x] white space
        [x] other:  <  ([{  >
    word start separators:
        [x] white space
        [x] other:  <  ([{  >

For 1.0 I'll see if I can quickly add the `(` to the prefix list to address this specific issue.

**Comment by andrey-yantsen** [comment]
Wasn't it fixed after #67 and release of v1.1.0?

**Comment by jasonblais** [comment]
cc @levb on above note from Andrey

**Comment by levb** [comment]
@andrey-yantsen #67 failed to be backwards compatible, but #71 introduced the `WordBoundary[=true]` link property to use the more standard `\b` word boundaries. If you turn it on, it should solve the `(` issue.
