### ISSUE TITLE
Collon not working in pattern

### ISSUE THREAD

**Issue by Tragen** [mattermost/mattermost-plugin-autolink#44]
I used the same samples like you did in your documentation but it doesn't work.
I broke it down to this

This is easy and works
`
                    {
                        "Pattern": "otrsxyz",
                        "Template": "works"
                    }
`

This is easy and works
`
                    {
                        "Pattern": "https//otrsxyz",
                        "Template": "works"
                    }
`

This doesn't work. Why?
`
                    {
                        "Pattern": "https://otrsxyz",
                        "Template": "works"
                    }
`

Did I miss something?

I also tried to replace the collon with .
`
                    {
                        "Pattern": "https.//otrsxyz",
                        "Template": "works"
                    }
`
but this doesn't work either.

Edit: I did more test. When I use the last pattern and
enter
https://otrsxyz
it's not getting replaced, but when I post
httpsx//otrsxyz
then it gets replaced.

**Comment by hanzei** [comment]
I think you must escape the `.`. Could you please try ` { "Pattern": "https\\.//otrsxyz", "Template": "works" }`

**Comment by Tragen** [comment]
I've tried that. It doesn't work.
It doesn't work when I post something with a :
Then the autolink doesn't recognize it even if the filter is correct.

**Comment by ohporter** [comment]
I can also confirm that **:** is an issue in patterns. With the latest plugin release, the supplied Jira examples in the README do not work.

This example does not match on https://mattermost.atlassian.net/browse/MM-1275
```
"Pattern": "(https://mattermost\\.atlassian\\.net/browse/)(MM)(-)(?P<jira_id>\\d+)",
```

Removing the colon does match on *https//mattermost.atlassian.net/browse/MM-1275*:
```
"Pattern": "(https//mattermost\\.atlassian\\.net/browse/)(MM)(-)(?P<jira_id>\\d+)",
```

Also, matching any character with a *.* replacing the *:* does not address the issue, it seems there's something mangling the url *:* parsing **before** it hits the regex parsing in the plugin.

**Comment by ohporter** [comment]
> I can also confirm that **:** is an issue in patterns. With the latest plugin release, the supplied Jira examples in the README do not work.
> 
> This example does not match on https://mattermost.atlassian.net/browse/MM-1275
> 
> ```
> "Pattern": "(https://mattermost\\.atlassian\\.net/browse/)(MM)(-)(?P<jira_id>\\d+)",
> ```
> 
> Removing the colon does match on _https//mattermost.atlassian.net/browse/MM-1275_:
> 
> ```
> "Pattern": "(https//mattermost\\.atlassian\\.net/browse/)(MM)(-)(?P<jira_id>\\d+)",
> ```
> 
> Also, matching any character with a _._ replacing the _:_ does not address the issue, it seems there's something mangling the url _:_ parsing **before** it hits the regex parsing in the plugin.

Following up to myself (as often happens), this seems to be fixed on master. I was running 0.4.0 and recently updated our server to a build of master to gain Scope support. I noticed that this example works as written now. Most likely this issue can be closed if all of the original author's issues are fixed as well.

**Comment by Tragen** [comment]
How can I update to master build?
Are there nightly builds somewhere?

**Comment by hanzei** [comment]
There are not nightly builds. But there will be a new version soon.

You can just build the plugin from source, if you have go installed.
