### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by swood** [mattermost/mattermost-plugin-autolink#46]
Hi. I wrote config below:
{ "Pattern": "(\\@group)", "Template": "@user1 @user2" }

and after reloaded config from disk, try to use this mention and nothing happened. 
Why? I did not see any messages in log of mattermost on error level.
Only messages below:
>{"level":"error","ts":1552568683.2504892,"caller":"plugin/client_rpc.go:469","msg":"RPC call MessageWillBePosted to plugin failed.","plugin_id":"}

Mattermost version is 5.8.0.
Plugin version is 0.4.0.

**Comment by jespino** [comment]
Can you check in your admin interface if the plugin is properly enabled and running?

**Comment by swood** [comment]
Hi, @jespino. It is precisely enabled and running. I have checked a process and it was in a container.

**Comment by swood** [comment]
I have restarted server and after I received messages below:

>{"level":"error","ts":1552597491.1394346,"caller":"log/log.go:289","msg":"forbidden content-type: \"text/html\"","source":"stdlog"}
{"level":"error","ts":1552597496.8059683,"caller":"plugin/client_rpc.go:469","msg":"RPC call MessageWillBePosted to plugin failed.","plugin_id":"mattermost-autolink","error":"connection is shut down"}
{"level":"error","ts":1552597497.7012339,"caller":"plugin/client_rpc.go:469","msg":"RPC call MessageWillBePosted to plugin failed.","plugin_id":"mattermost-autolink","error":"connection is shut down"}

I suppose it is something like "broken API", isn't it?

**Comment by hanzei** [comment]
Hey @swood,

Would you be open to providing more of your log file?

What setup are you using? Docker, stand alone, nginx? What Mattermost server version are you running?

**Comment by swood** [comment]
Hey, @hanzei.
Unfortunately, there is not some other log. My instance runs in Docker and it is my image with standard binary. As I mentioned, Mattermost version is 5.8.0.

**Comment by hanzei** [comment]
If you turn debug logging on, do you see more related log messages?

**Comment by swood** [comment]
Hi, @hanzei.
Unfortunately, no. All relevant messages below:
>{"level":"error","ts":1552902767.3635442,"caller":"plugin/client_rpc.go:469","msg":"RPC call MessageWillBePosted to plugin failed.","plugin_id":"mattermost-autolink","error":"connection is shut down"}
{"level":"debug","ts":1552902767.3935654,"caller":"app/notification_push.go:210","msg":"Clearing push notification to  with channel_id xps3nthh8fg59knm6i8x1mn1nh"}

But it the same that I sent before. Do you have installation of this plugin and server with version 5.8.0? Maybe RPC-protocol has been changed between versions of server?

**Comment by hanzei** [comment]
> Do you have installation of this plugin and server with version 5.8.0?

Yes. This plugin is running on the Mattermost Community server.

> Maybe RPC-protocol has been changed between versions of server?

I doubt this.

@crspeller Could you please take a look at this issue, as you worked on a similar one before?

**Comment by swood** [comment]
Hey, @hanzei and @crspeller. Do you have any updates with my issue?

**Comment by crspeller** [comment]
@swood Looks like the plugin is crashing. Possibly because of a config error. Can you post your full plugin config? I may give us a clue as to what is happening.

**Comment by pjenicot** [comment]
@swood I had the same problem when I overwritten the existing plugin "mattermost-autolink" (v.0.4.0).

> please  uninstall the old plugin and install the new version

```
Server log:
{"level":"error","ts":1555061822.1290948,"caller":"web/context.go:52","msg":"Unable to install plugin. A plugin with the same ID is already installed.","path":"/api/v4/plugins"
```

**Comment by hanzei** [comment]
@pjenicot How you need to uninstall the old version of the plugin first.

**Comment by Tragen** [comment]
I have the same problem. Plugin was working and I only changed the Patterns. Now I get the also "connection is shut down"

**Comment by Tragen** [comment]
I found my error. It was an error in the config file above the plugin section.

**Comment by ThiefMaster** [comment]
@Tragen, could you share what kind of error it was? The plugin (0.5.0) is crashing for me as well (segfault as seen in the debug log), and my config is perfectly valid and works on another system...

**Comment by Tragen** [comment]
For me it was that I entered some characters accidentally.
Instead of
`        "Parameter": true` 
I had something like
`ssss        "Parameter": true`

**Comment by ThiefMaster** [comment]
OK, so it was just a syntax error :)

**Comment by Tragen** [comment]
I had this syntax error shortly above the plugins configuration, so the rest was working.
In my opinion, MM shouldn't start at all with errors in the config.

**Comment by Tragen** [comment]
The error `connection is shut down` happened again without any other erros.
I restarted MM and it's working again.

`{"level":"error","ts":1555586147.6802464,"caller":"mlog/log.go:172","msg":"RPC call MessageWillBePosted to plugin failed.","plugin_id":"mattermost-autolink","error":"connection is shut down"}
{"level":"info","ts":1555586155.4858947,"caller":"scheduler/worker.go:78","msg":"Worker: Job is complete","worker":"Plugins","job_id":"d4bawh234fadfadfasd9kqmqjc"}
{"level":"error","ts":1555586170.4084165,"caller":"mlog/log.go:172","msg":"RPC call MessageWillBePosted to plugin failed.","plugin_id":"mattermost-autolink","error":"connection is shut down"}
{"level":"error","ts":1555586183.911014,"caller":"mlog/log.go:172","msg":"RPC call MessageWillBePosted to plugin failed.","plugin_id":"mattermost-autolink","error":"connection is shut down"}`

**Comment by Tragen** [comment]
I'm using MM 5.10.0 with Plugin 0.5.0

**Comment by ThiefMaster** [comment]
0.5.0 is completely broken atm - ANY direct message crashes the plugin. downgrade to 0.4 or if you trust me enough you can use the version i built that contains the fix from my PR: https://github.com/ThiefMaster/mattermost-plugin-autolink/releases/tag/v0.5.0-20190418

**Comment by Tragen** [comment]
I don't know you but the code changes were small and look good. ;)
Thank you very much. I will try it now.

**Comment by jespino** [comment]
@Tragen please, try with the new published 0.5.1 version.

**Comment by hanzei** [comment]
@Tragen Did you try with the latest version of this plugin?

**Comment by Tragen** [comment]
Latest version is working fine for me. Thanks.

**Comment by hanzei** [comment]
Thanks for the update @Tragen. Closing this one for now. Feel free to reopen if the issue comes up again.
