### ISSUE TITLE
Update README for #43, #71

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-autolink#57]
In first paragraph of Usage section, clarify that autolinks having three parts - pattern, template and scope.

https://github.com/mattermost/mattermost-plugin-autolink/pull/43 added an optional scope parameter to define which team/channel the defined autolink applies to. 

https://github.com/mattermost/mattermost-plugin-autolink/pull/71 added the /autolink command, and the `WordBoundary`, `Disabled`, and `Name` link attributes.

**Comment by rohanjulka19** [comment]
Opened a PR for this issue . #72

**Comment by jasonblais** [comment]
Thank you @rohanjulka19! Really appreciated 👍
