### ISSUE TITLE
Allow channel admins create custom groups

### ISSUE THREAD

**Issue by felibb** [mattermost/mattermost-plugin-autolink#58]
We have a case for the plugin where channel admins would like to create custom group mentions ad-hoc (`@customgroup*`). Currently this requires console access to the server, and is neither feasible nor scalable. Example: HipChat used to have an [Alias](https://marketplace.atlassian.com/apps/1211973/alias?hosting=server&tab=overview) plugin to accomplish this. I wonder if Autolink can have similar functionality. Even if it can be configured permanently per channel without requiring system admin permissions, it would be good enough.

**Comment by levb** [comment]
#71 adds the ability to edit the configuration with a `/autolink set` command. Will it solve the issue, @felibb?

**Comment by felibb** [comment]
@levb I can say only after we test it, but looks promising.

Will it have an ability to include @-usernames to the link? Sorry, a bit unclear.

**Comment by levb** [comment]
You can do something like `/autolink set Template @user1 @user2 ...`. I understand that this is a rather small improvement, far from offering a UI picker and other advanced features, but it should help somewhat.

**Comment by felibb** [comment]
Right, I understand. FWIW I think it can be created backwards, i.e. type out all the names with the help of the standard picker, then prepend the command and flags.

Would you recommend waiting for the plugin to be included in the server installer, or manual installation? If former, any idea on the ETA?

**Comment by jfrerich** [comment]
Hi @felibb!  

It has been a while since you have been updated with latest autolink plugin progress.  I'd like to inform you of some of the updates.  The PR referenced in this issue has been released.  You can get the update via server upgrade, manual installation, or most recently the Plugin Marketplace.  You can find the Plugin Marketplace in the hamburger menu above the channel listings.  This will allow you to upgrade the autolink plugin via a simple button click.

I will also investigate the original intent of this issue (allow channel admins to edit the config) and get back to you with an answer. but I first wanted to just check in and give you these updates.  

Please let me know if you have any problems accessing the new `/autolink set` feature once you upgrade the plugin!

**Comment by felibb** [comment]
Hi @jfrerich,

Creating a custom mention works for us, thanks. It even shows a user picker when I start typing @-mention to populate a group.

> I will also investigate the original intent of this issue (allow channel admins to edit the config) and get back to you with an answer. but I first wanted to just check in and give you these updates.

In my mind restricting the create/edit autolink permissions to a smaller group of channel admins would allow us to keep the amount of autolinks in check, and avoid polluting the global config. Alternatively the plugin config could be moved out to a separate file, then I would feel comfortable opening these permissions to every user.

**Comment by jfrerich** [comment]
@felibb, thanks for checking back and with the feedback you provided. Regarding the channel level permissions, I will discuss with my team and get you a response!

**Comment by levb** [comment]
What we can add easily as a configurable list of "plugin admins" who would be allowed to run the /autolink command. Will that work for you, @felibb ?

**Comment by felibb** [comment]
Yes, plugin admin group would work. Probably even more restrictive than channel admins.

BTW is the relevant permission "Manage Slash Commands"? It is enabled for system and team admins right now, but not for All Members, and we tested yesterday with a regular user, with the following result:

![Image Pasted at 2020-1-20 21-46](https://user-images.githubusercontent.com/4253456/72779377-705f3b80-3c24-11ea-8bac-bf9682e3fd34.png)

**Comment by levb** [comment]
They have to be a "proper" full sysadmin, 
![image](https://user-images.githubusercontent.com/1187448/72809985-99c29c00-3c11-11ea-8307-8b25488fd2d4.png)

**Comment by levb** [comment]
Filed https://github.com/mattermost/mattermost-plugin-autolink/issues/84 to add plugin admins
