### ISSUE TITLE
v1.0.0 plugin bundle missing?

### ISSUE THREAD

**Issue by lkraav** [mattermost/mattermost-plugin-autolink#59]
Is there supposed to be a download link at https://github.com/mattermost/mattermost-plugin-autolink/releases/tag/v1.0.0 not sure?

**Comment by uhlhosting** [comment]
I get a Encountered an error when extracting the plugin. Review your plugin file content and try again. When upgrading.

**Comment by crspeller** [comment]
Yes. There was supposed to be. The automation wasn't setup for this repository. PR here: https://github.com/mattermost/mattermost-plugin-autolink/pull/60

I made a release manually with the appropriate binary!
