### ISSUE TITLE
Update README.md file with link to online regex tester

### ISSUE THREAD

**Issue by LocalHeroPro** [mattermost/mattermost-plugin-autolink#61]
Update README.md file with proper with that plugin regex tester for Golang.
For example:

1. https://regex-golang.appspot.com/assets/html/index.html
2. https://regex101.com/
3. another one.

**Comment by hanzei** [comment]
Hey @LocalHeroPro,

Great idea! Would you be open on submitting a PR for this?

**Comment by LocalHeroPro** [comment]
Created #62
