### ISSUE TITLE
Escaping non special chars in the Pattern

### ISSUE THREAD

**Issue by LocalHeroPro** [mattermost/mattermost-plugin-autolink#63]
If I wan't to use for example that link:
```url
https://example.atlassian.net/secure/RapidBoard.jspa?rapidView=92&projectKey=EX&modal=detail&selectedIssue=EX-92
```
I have to write that working pattern:
```json5
(https://example\\.atlassian\\.net/secure/RapidBoard\\.jspa\\?rapidView=)(?P\u003crapid_view\u003e\\d+)(\u0026projectKey\\=)(?P\u003cproject_key\u003e[A-Z1-9]{2,4})(\u0026modal\\=detail\u0026selectedIssue\\=)(?P\u003cjira_code\u003e[A-Z1-9]{2,4})(-)(?P\u003cjira_id\u003e\\d+)
```
So I have to double escape `=`, `.`, `d+`, instead single escape or even non escape (for `=`).
If I check regex in the online checker, that behavior fail, but in MM config works.
I have to mention: pattern and template are changed after MM is restarted (for example from `<` to `\u003e`), can we prevent from it? In that way pattern and template are less readable.

**Comment by levb** [comment]
@LocalHeroPro #71 added the ability to view and edit the autolink config with the `/autolink` command. The command displays and accepts raw text for Pattern/Template, so should clarify somewhat. 2/5  properly escaping regexp in JSON is painful, the less we expose the users to the encoded text, the better.
