### ISSUE TITLE
Code blocks still broken in some cases

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/mattermost-plugin-autolink#7]
In this case, *test* is not converted, since the plugin thinks it's inside a fenced codeblock - but it's not, since the fences are in separate code blocks started by the four-space indentation:

```
    ```

test

    ```
```

---

Another case of thinking *test* is inside a fenced code block even though it isn't:

```
` ``` `
test
` ``` `
```

---

In this case, *test* is converted even though it is inside a code block (created by the four-space indentation:

```
    test
```

---

I think the cleanest solution here would be using a markdown parser, i.e. convert to an AST, apply the linkification on text that is neither part of an existing link, nor inside a code block nor inline code. Like this it wouldn't matter to the plugin how the code block is created at all.

**Comment by coreyhulen** [comment]
I agree, I would love to switch over to https://github.com/mattermost/mattermost-server/tree/master/utils/markdown but it isn't fully featured yet.

**Comment by ThiefMaster** [comment]
Yeah, looks like it would be pretty easy to use if `Text` objects exposed a `Range` (then the same logic currently used for image proxy link conversion could be used)

**Comment by ThiefMaster** [comment]
I played around a bit with the markdown parser and this seems to work, at least for the test cases I added: https://gist.github.com/ThiefMaster/ad150a9d461c1cb3d12e708618ab83ba

**Comment by coreyhulen** [comment]
@ThiefMaster this is awesome.  Do you mind submitting a PR?

**Comment by ThiefMaster** [comment]
Sure, I can do that.  Just wanted to get an opinion on it first.

Is there any decent way to use a local clone of mattermost instead of the vendorized version? Editing stuff inside the vendor folder was fine to test this out, but I guess the PR for the markdown parser should be against the main mattermost repo - and copying that whole folder into the plugin's vendor dir to run e.g. the plugin's tests would be somewhat cumbersome.

**Comment by coreyhulen** [comment]
I think you can point it at your fork in go dep using one of their overrides like we do for gorp.  It might be easier to just submit the mattermost-server PR first, get that merged then I can update the vendor dir and you can submit your PR here after that.

**Comment by ThiefMaster** [comment]
Sure, this was more about having a less messy way to test things locally

**Comment by coreyhulen** [comment]
ahh...then I think you can do something like https://github.com/mattermost/mattermost-server/blob/master/Gopkg.toml#L44 and point it to your fork?

**Comment by coreyhulen** [comment]
or https://github.com/mattermost/mattermost-server/blob/master/Gopkg.toml#L50 (sorry it's been awhile since I've don this)

**Comment by ThiefMaster** [comment]
still requires commit+push, but i'll see if i can maybe just use a good old symlink there that points to my local source...

**Comment by ThiefMaster** [comment]
@coreyhulen just opened a PR for this: mattermost/mattermost-server#9067

**Comment by coreyhulen** [comment]
Awesome...thanks!
