### ISSUE TITLE
Text containing multiple links doesn't always render correctly

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-autolink#8]
Repro:
1) Post the following text to a channel on pre-release.mattermost.com

``
Do we need to merge the translations PRs (https://github.com/mattermost/mattermost-server/pull/8998 and https://github.com/mattermost/mattermost-webapp/pull/1378) before your localization changes in https://github.com/mattermost/mattermost-server/pull/8987.
``

Observed:

![image](https://user-images.githubusercontent.com/13119842/41917173-be1df526-7927-11e8-86e2-1d39c887729e.png)

Expected:
![image](https://user-images.githubusercontent.com/13119842/41917254-eae9484e-7927-11e8-8621-748ce6a61da9.png)

Note: When I re-edit the message, I see this in the Edit dialog

```
Do we need to merge the translations PRs (https://github.com/mattermost/mattermost-server/pull/8998 and [pr-mattermost-webapp/pull/1378) before your localization changes in https://github.com/mattermost/mattermost-server-8987](https://github.com/mattermost/mattermost-webapp/pull/1378) before your localization changes in https://github.com/mattermost/mattermost-server/pull/8987).
```

**Comment by coreyhulen** [comment]
Yeah the ones in () probably shouldn't autolink since it thinks it might be part of something else.  It needs to start with whitespace or somethings similar.  Fixing issue #7 (switching to an AST) should improve this.

Not autolinking the last one looks like a bug.

**Comment by ThiefMaster** [comment]
Whethe text inside `(...)` should be skipped or not should probably be configurable.

When replacing e.g. bugtracker ticket numbers having them replaced inside `()` seems very much wanted. 

 > Check the issue about foo (FOO-1337) what you think

IMO that should be linkified.

**Comment by coreyhulen** [comment]
I think this is fixed with https://github.com/mattermost/mattermost-plugin-autolink/pull/25
