### ISSUE TITLE
Add the concept of plugin admin users

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-autolink#84]
Add a (visible, editable in admin console) section to autolink config to define the list of plugin administrators. It should take a list of @usernames, ideally with autocomplete.

These users should then be allowed to execute the `/autolink` command.

An rough prototype can be found in 
- https://github.com/mattermost/mattermost-plugin-solar-lottery/blob/e41d9d22ad8f4ebd5164631b99441ad3548ea4ab/plugin.json#L20-L25
- https://github.com/mattermost/mattermost-plugin-solar-lottery/blob/dev/server/plugin/api.go#L21

But it lacks accepting @usernames with autocomplete.

![image](https://user-images.githubusercontent.com/1187448/72811054-b6f86a00-3c13-11ea-8b9d-2163d4467b40.png)

**Comment by vespian** [comment]
@levb Basing on [1], by default there is a `username` type of the field with autocompletion, but it is meant to choose one user, not a list. If one wants to have multi-user support, a custom field needs to be created, but this requires some extra web code, just like in e.g. [2]. Right? 


[1] https://developers.mattermost.com/extend/plugins/manifest-reference/#settings_schema.settings.type
[2] https://github.com/mattermost/mattermost-plugin-custom-attributes/blob/14027463acf04ecea5a0d5f2b3abfe80959f3a80/webapp/src/index.js#L12

**Comment by levb** [comment]
@vespian You're right, we do not have the appropriate input type. I do not believe that investing in custom UI work is worth it in this case. How about we allow a ` `- or `,`-separated list of strings, where each one can be a mattermost user ID, or a `[@]username`?

**Comment by vespian** [comment]
> How about we allow a - or ,-separated list of strings, where each one can be a mattermost user ID, or a [@]username?

+1

**Comment by vespian** [comment]
I would like to give it a try.

**Comment by vespian** [comment]
@levb Please have a look at https://github.com/mattermost/mattermost-plugin-autolink/pull/93
