### ISSUE TITLE
Performance: do not fetch extra post data unless needed

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-autolink#87]
Presently, processing each post autolink goes back to the server to get the Channel and Team names for it, to match the scope. https://github.com/mattermost/mattermost-plugin-autolink/blob/0c286d8baa27c03834c2240c0e20fd518b4ec83d/server/autolinkplugin/plugin.go#L104-L117

1. These should be requested lazily so if no links have `Scope` defined, there's no perf impact.
2. Long term we should consider a new hook `MessageWillBePostedEx` that would contain extended metadata (channel and team names in this case) and will not require extra roundtrips. cc @lieut-data 
3. Another long-term performance improvement here would be limiting the `Scope` to perform only exact matches on teams and channels, rather than the present `contains` (by keyword). Maybe we add new fields `Channel` and `Team` that are exact matches? This would allow pre-resolving all references on Config and comparing by ID, avoiding the extra per-message RPCs.

**Comment by lieut-data** [comment]
@ali-farooq0, this will be an interesting case to think through with respect to autolink performance efforts. Knowing the RPC overhead, in particular, will influence where in the pipeline we should optimize.

**Comment by mo2menelzeiny** [comment]
Hello @levb @hanzei 
I would love to work on this
