### ISSUE TITLE
Move autolink to use a store backed by PluginAPI rather than the config

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-autolink#89]
#### Summary
Currently, the autolink configuration is stored in `config.json`.  This request is to migrate the configuration into the store.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22001

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Autolink" community channel](https://community.mattermost.com/core/channels/plugin-autolink
).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by mo2menelzeiny** [comment]
@jfrerich I would like to work on this, but I need more information on the store, what exactly are you referring to?

**Comment by levb** [comment]
@mo2menelzeiny I started answering your question, and realized that I don't have a very good answer it is a lot more complicated of an issue than we first though. I'm going to temporarily remove this ticket from the "Help Wanted" bucket for us to think through what we want to accomplish here.

**Comment by jfrerich** [comment]
Thanks for the inquiry, @mo2menelzeiny.  As Lev mentioned, we will have to define spec a little better before opening this ticket back `Up For Grabs`.  If you still interested in making a contribution, feel free to check out the `HW` and `Up For Grabs` issues in our plugin repos.  Here's the [link](https://github.com/issues?utf8=%E2%9C%93&q=repo%3Amattermost%2Fmattermost-plugin-antivirus+repo%3Amattermost%2Fmattermost-plugin-autolink+repo%3Amattermost%2Fmattermost-plugin-aws-SNS+repo%3Amattermost%2Fmattermost-plugin-confluence+repo%3Amattermost%2Fmattermost-plugin-custom-attributes+repo%3Amattermost%2Fmattermost-plugin-demo+repo%3Amattermost%2Fmattermost-plugin-oembed+repo%3Amattermost%2Fmattermost-plugin-giphy+repo%3Amattermost%2Fmattermost-plugin-github+repo%3Amattermost%2Fmattermost-plugin-gitlab+repo%3Amattermost%2Fmattermost-plugin-google-calendar+repo%3Amattermost%2Fmattermost-plugin-jenkins+repo%3Amattermost%2Fmattermost-plugin-jira+repo%3Amattermost%2Fmattermost-plugin-memes+repo%3Amattermost%2Fmattermost-plugin-mscalendar+repo%3Amattermost%2Fmattermost-plugin-nps+repo%3Amattermost%2Fmattermost-plugin-suggestions+repo%3Amattermost%2Fmattermost-plugin-skype4business+repo%3Amattermost%2Fmattermost-plugin-solar-lottery+repo%3Amattermost%2Fmattermost-plugin-todo+repo%3Amattermost%2Fmattermost-plugin-webex+repo%3Amattermost%2Fmattermost-plugin-welcomebot+repo%3Amattermost%2Fmattermost-plugin-zoom+is%3Aopen+is%3Aissue+archived%3Afalse+label%3A%22help%20wanted%22%20label%3A%22up%20for%20grabs%22%20) with lots of options!

**Comment by levb** [comment]
There's no cache invalidation mechanism for KV records, so it'd be difficult to propagate config changes timely; the only mechanism that comes to mind as immediately available is `OnConfigurationChange` which of course defeats the purpose.

**Comment by hanzei** [comment]
@levb Could you elaborate what exactly `timely` mean? Is e.g. propagating changes every minute fine?
