### ISSUE TITLE
`help` command output is not formatting correctly.

### ISSUE THREAD

**Issue by sadohert** [mattermost/mattermost-plugin-autolink#95]
Testing with the latest release (v1.1.2).

Server:
Mattermost Version: 5.18.2
Database Schema Version: 5.18.0
Database: postgres

The output from running `/autolink help` appears below.  It looks like its meant to be a nicely formatted markdown message, but its all coming through raw for me which makes it difficult to parse the instructions on how to setup autolink relationships.

![image](https://user-images.githubusercontent.com/260544/76009213-d8b96200-5ede-11ea-9e71-2130bd4e4695.png)

**Comment by hanzei** [comment]
I can't repo this problem with the latest MM `master`. Would you mind re testing it on 5.20?

**Comment by levb** [comment]
Looks good to me, too. Not repro?

**Comment by sadohert** [comment]
Sorry for the delay... just attempted to repro, and it worked fine on 5.20.x
