### ISSUE TITLE
Setting Scope is not mentioned in help text

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-autolink#96]
Using scope to refine when an autolink pattern is applied is functional and mentioned in the read-me but it is missing from help.

when using `/autolink help`  there should be a mention and example of `/autolink set scope`

**Comment by mo2menelzeiny** [comment]
Hey @hanzei
I've submitted a pull request for this if you care to check it out

**Comment by hanzei** [comment]
Awesome, thanks for the quick PR @mo2menelzeiny :+1:
