### ISSUE TITLE
Migrate logging to use RPC Logging methods

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-autolink#99]
Instead of using `mlog` all log calls should use the RPC methods `LogX`, e.g. [`LogDebug`](https://developers.mattermost.com/extend/plugins/server/reference/#API.LogDebug). This allows the server to gradually select which log messages to show in the server logs.

**Comment by mo2menelzeiny** [comment]
@hanzei, I'm giving this a shot.
I don't know if this is the right place, but I'm having trouble with the testing.
Does any test cases cover the thrown errors? or do I have to manually test this?

My thoughts are for example
```
if err != nil {
        mlog.Error(fmt.Sprintf("Error creating autolinker: %+v: %v", c.Links[i], err))
}
```
I'm going to replace it with 
```
if err != nil {
	p.API.LogError(fmt.Sprintf("Error creating autolinker: %+v: %v", c.Links[i], err))
}
```
But how can I validate my change?

**Comment by hanzei** [comment]
@mo2menelzeiny Please see my response in your PR: https://github.com/mattermost/mattermost-plugin-autolink/pull/102#issuecomment-602677926
